### ISSUE TITLE
Which llvm version is required?

### ISSUE THREAD

**Issue by paceholder** [russelltg/chigraph#40]
I have some compilation troubles.

The function `llvm::parseType()` used at `libchig/src/LangModule.cpp:410:16` is not defined in my `llvm-3.8`

As I see, it was added quite recently just [this year](https://github.com/llvm-mirror/llvm/commit/2ba0323edd1a49c7a78404e1814dcd00818f65c0).

Are you using the latest dev sources of `llvm`?

**Comment by russelltg** [comment]
I am using 3.9, but I'll remove that function quickly to use what I was
using before to fix that :).

3.9 is just too new to require.

**Comment by paceholder** [comment]
off-topic: can you suggest tome decent introduction materials to llvm? theory/slides/manuals? Thanks!

**Comment by russelltg** [comment]
Yeah, the best one is the [Kaleidoscope tutorial](http://llvm.org/docs/tutorial/) which is a complete guide on implementing a language + JIT + debug info + optimization. 

Also if you have questions on how to use the `IRBuilder` if you boot up a VM with an old version of llvm (3.0 or earlier) you can use the `cpp` backend to compile some C code:

`clang main.c -S -o - -emit-llvm | llc -march=cpp` and that will emit the C++ code required to generate that LLVM. 

It doesn't use the `IRBuilder` class, but it's pretty easy to convert their calls to calls to `IRBuilder`

**Comment by russelltg** [comment]
Fixed in https://github.com/russelltg/chigraph/commit/c2be958b481a6604dae3907c1cadc748e6e3d6b5
